/**
 * Static device specs catalog, keyed by "brand|model".
 * Storage variants share the same specs — only storage_gb differs.
 * Sourced from GSMArena / manufacturer spec sheets.
 */

export type DeviceSpecs = {
  display: string;        // e.g. "6.1\" OLED"
  display_hz?: string;    // e.g. "120 Hz" (omit if 60 Hz standard)
  camera_main: string;    // e.g. "48 MP"
  camera_front: string;   // e.g. "12 MP"
  processor: string;      // e.g. "Apple A16 Bionic"
  ram_gb: number;
  battery_mah: number;
  sim: string;            // e.g. "eSIM + Nano-SIM"
  connectivity: string[]; // e.g. ["5G", "WiFi 6E", "NFC", "Bluetooth 5.3"]
  year: number;
};

const SPECS: Record<string, DeviceSpecs> = {
  // ── Apple ─────────────────────────────────────────────────────────────────

  "Apple|iPhone 16 Pro Max": {
    display: "6.9\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A18 Pro",
    ram_gb: 8,
    battery_mah: 4685,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Apple|iPhone 16 Pro": {
    display: "6.3\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A18 Pro",
    ram_gb: 8,
    battery_mah: 3582,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Apple|iPhone 16 Plus": {
    display: "6.7\" OLED",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A18",
    ram_gb: 8,
    battery_mah: 4674,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Apple|iPhone 16": {
    display: "6.1\" OLED",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A18",
    ram_gb: 8,
    battery_mah: 3561,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Apple|iPhone 15 Pro Max": {
    display: "6.7\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A17 Pro",
    ram_gb: 8,
    battery_mah: 4422,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Apple|iPhone 15 Pro": {
    display: "6.1\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A17 Pro",
    ram_gb: 8,
    battery_mah: 3274,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Apple|iPhone 15 Plus": {
    display: "6.7\" OLED",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A16 Bionic",
    ram_gb: 6,
    battery_mah: 4383,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Apple|iPhone 15": {
    display: "6.1\" OLED",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A16 Bionic",
    ram_gb: 6,
    battery_mah: 3877,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Apple|iPhone 14 Pro Max": {
    display: "6.7\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A16 Bionic",
    ram_gb: 6,
    battery_mah: 4323,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2022,
  },
  "Apple|iPhone 14 Pro": {
    display: "6.1\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "12 MP",
    processor: "Apple A16 Bionic",
    ram_gb: 6,
    battery_mah: 3200,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2022,
  },
  "Apple|iPhone 14 Plus": {
    display: "6.7\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 6,
    battery_mah: 4323,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2022,
  },
  "Apple|iPhone 14": {
    display: "6.1\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 6,
    battery_mah: 3279,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2022,
  },
  "Apple|iPhone 13 Pro Max": {
    display: "6.7\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 6,
    battery_mah: 4352,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NCI", "UWB"],
    year: 2021,
  },
  "Apple|iPhone 13 Pro": {
    display: "6.1\" OLED ProMotion",
    display_hz: "120 Hz",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 6,
    battery_mah: 3095,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2021,
  },
  "Apple|iPhone 13": {
    display: "6.1\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 4,
    battery_mah: 3227,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2021,
  },
  "Apple|iPhone 13 mini": {
    display: "5.4\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 4,
    battery_mah: 2438,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2021,
  },
  "Apple|iPhone 12 Pro Max": {
    display: "6.7\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A14 Bionic",
    ram_gb: 6,
    battery_mah: 3687,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2020,
  },
  "Apple|iPhone 12 Pro": {
    display: "6.1\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A14 Bionic",
    ram_gb: 6,
    battery_mah: 2815,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2020,
  },
  "Apple|iPhone 12": {
    display: "6.1\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A14 Bionic",
    ram_gb: 4,
    battery_mah: 2815,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2020,
  },
  "Apple|iPhone 12 mini": {
    display: "5.4\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A14 Bionic",
    ram_gb: 4,
    battery_mah: 2227,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2020,
  },
  "Apple|iPhone 11 Pro Max": {
    display: "6.5\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A13 Bionic",
    ram_gb: 4,
    battery_mah: 3969,
    sim: "eSIM + Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2019,
  },
  "Apple|iPhone 11 Pro": {
    display: "5.8\" OLED",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A13 Bionic",
    ram_gb: 4,
    battery_mah: 3046,
    sim: "eSIM + Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2019,
  },
  "Apple|iPhone 11": {
    display: "6.1\" IPS LCD",
    camera_main: "12 MP",
    camera_front: "12 MP",
    processor: "Apple A13 Bionic",
    ram_gb: 4,
    battery_mah: 3110,
    sim: "eSIM + Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC"],
    year: 2019,
  },
  "Apple|iPhone SE (3rd gen)": {
    display: "4.7\" IPS LCD",
    camera_main: "12 MP",
    camera_front: "7 MP",
    processor: "Apple A15 Bionic",
    ram_gb: 4,
    battery_mah: 2018,
    sim: "eSIM + Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC"],
    year: 2022,
  },
  "Apple|iPhone SE (2nd gen)": {
    display: "4.7\" IPS LCD",
    camera_main: "12 MP",
    camera_front: "7 MP",
    processor: "Apple A13 Bionic",
    ram_gb: 3,
    battery_mah: 1821,
    sim: "eSIM + Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC"],
    year: 2020,
  },
  "Apple|iPhone XR": {
    display: "6.1\" IPS LCD",
    camera_main: "12 MP",
    camera_front: "7 MP",
    processor: "Apple A12 Bionic",
    ram_gb: 3,
    battery_mah: 2942,
    sim: "eSIM + Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC"],
    year: 2018,
  },
  "Apple|iPhone XS": {
    display: "5.8\" OLED",
    camera_main: "12 MP",
    camera_front: "7 MP",
    processor: "Apple A12 Bionic",
    ram_gb: 4,
    battery_mah: 2658,
    sim: "eSIM + Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC"],
    year: 2018,
  },

  // ── Samsung ───────────────────────────────────────────────────────────────

  "Samsung|Galaxy S24 Ultra": {
    display: "6.8\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "200 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Samsung|Galaxy S24+": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 4900,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Samsung|Galaxy S24": {
    display: "6.2\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 8,
    battery_mah: 4000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Samsung|Galaxy S24 FE": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Exynos 2500",
    ram_gb: 8,
    battery_mah: 4700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Samsung|Galaxy S23 Ultra": {
    display: "6.8\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "200 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Samsung|Galaxy S23+": {
    display: "6.6\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 8,
    battery_mah: 4700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Samsung|Galaxy S23": {
    display: "6.1\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 8,
    battery_mah: 3900,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Samsung|Galaxy S23 FE": {
    display: "6.4\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 1",
    ram_gb: 8,
    battery_mah: 4500,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.1", "NFC"],
    year: 2023,
  },
  "Samsung|Galaxy S22 Ultra": {
    display: "6.8\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "108 MP",
    camera_front: "40 MP",
    processor: "Snapdragon 8 Gen 1",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.2", "NFC", "UWB"],
    year: 2022,
  },
  "Samsung|Galaxy S22+": {
    display: "6.6\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 1",
    ram_gb: 8,
    battery_mah: 4500,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.2", "NFC", "UWB"],
    year: 2022,
  },
  "Samsung|Galaxy S22": {
    display: "6.1\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 1",
    ram_gb: 8,
    battery_mah: 3700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.2", "NFC", "UWB"],
    year: 2022,
  },
  "Samsung|Galaxy S21 Ultra": {
    display: "6.8\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "108 MP",
    camera_front: "40 MP",
    processor: "Snapdragon 888",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2021,
  },
  "Samsung|Galaxy S21": {
    display: "6.2\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 888",
    ram_gb: 8,
    battery_mah: 4000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC", "UWB"],
    year: 2021,
  },
  "Samsung|Galaxy S21 FE": {
    display: "6.4\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "32 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 888",
    ram_gb: 6,
    battery_mah: 4500,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.0", "NFC"],
    year: 2022,
  },
  "Samsung|Galaxy A55": {
    display: "6.6\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Exynos 1480",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Samsung|Galaxy A35": {
    display: "6.6\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Exynos 1380",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Samsung|Galaxy A25": {
    display: "6.5\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Exynos 1280",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 5", "Bluetooth 5.1", "NFC"],
    year: 2024,
  },
  "Samsung|Galaxy A15": {
    display: "6.5\" AMOLED",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Dimensity 6100+",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Samsung|Galaxy A54": {
    display: "6.4\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Exynos 1380",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Samsung|Galaxy A34": {
    display: "6.6\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "13 MP",
    processor: "Dimensity 1080",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 5", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Samsung|Galaxy A24": {
    display: "6.5\" AMOLED",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Helio G99",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.2", "NFC"],
    year: 2023,
  },
  "Samsung|Galaxy A14": {
    display: "6.6\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Exynos 850",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.2", "NFC"],
    year: 2023,
  },
  "Samsung|Galaxy A05s": {
    display: "6.7\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Snapdragon 680",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.1"],
    year: 2023,
  },
  "Samsung|Galaxy A04s": {
    display: "6.5\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "5 MP",
    processor: "Exynos 850",
    ram_gb: 3,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0"],
    year: 2022,
  },
  "Samsung|Galaxy Z Fold 6": {
    display: "7.6\" AMOLED (inner)",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 4400,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Samsung|Galaxy Z Flip 6": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 4000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Samsung|Galaxy Z Fold 5": {
    display: "7.6\" AMOLED (inner)",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 12,
    battery_mah: 4400,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Samsung|Galaxy Z Flip 5": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "12 MP",
    camera_front: "10 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 8,
    battery_mah: 3700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },

  // ── Xiaomi ────────────────────────────────────────────────────────────────

  "Xiaomi|14 Pro": {
    display: "6.73\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 4880,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2023,
  },
  "Xiaomi|14": {
    display: "6.36\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 4610,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2023,
  },
  "Xiaomi|13T Pro": {
    display: "6.67\" AMOLED",
    display_hz: "144 Hz",
    camera_main: "50 MP",
    camera_front: "20 MP",
    processor: "Dimensity 9200+",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2023,
  },
  "Xiaomi|13T": {
    display: "6.67\" AMOLED",
    display_hz: "144 Hz",
    camera_main: "50 MP",
    camera_front: "20 MP",
    processor: "Dimensity 8200 Ultra",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Xiaomi|13 Pro": {
    display: "6.73\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 12,
    battery_mah: 4820,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Xiaomi|13": {
    display: "6.36\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "54 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 8,
    battery_mah: 4500,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Xiaomi|12T Pro": {
    display: "6.67\" AMOLED",
    display_hz: "144 Hz",
    camera_main: "200 MP",
    camera_front: "20 MP",
    processor: "Snapdragon 8+ Gen 1",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2022,
  },
  "Xiaomi|12T": {
    display: "6.67\" AMOLED",
    display_hz: "144 Hz",
    camera_main: "108 MP",
    camera_front: "20 MP",
    processor: "Dimensity 8100 Ultra",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2022,
  },
  "Xiaomi|Redmi Note 13 Pro+": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "200 MP",
    camera_front: "16 MP",
    processor: "Dimensity 7200 Ultra",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Xiaomi|Redmi Note 13 Pro": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "200 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 7s Gen 2",
    ram_gb: 8,
    battery_mah: 5100,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 6", "Bluetooth 5.2", "NFC"],
    year: 2024,
  },
  "Xiaomi|Redmi Note 13": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "108 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 685",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.1", "NFC"],
    year: 2024,
  },
  "Xiaomi|Redmi Note 12 Pro": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Dimensity 1080",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.2", "NFC"],
    year: 2023,
  },
  "Xiaomi|Redmi Note 12": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Snapdragon 4 Gen 1",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC"],
    year: 2023,
  },
  "Xiaomi|Redmi 13C": {
    display: "6.74\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "5 MP",
    processor: "Helio G85",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.3"],
    year: 2023,
  },
  "Xiaomi|Redmi 12": {
    display: "6.79\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "8 MP",
    processor: "Helio G88",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Xiaomi|Poco X6 Pro": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "16 MP",
    processor: "Dimensity 8300-Ultra",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "Xiaomi|Poco X6": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 7s Gen 2",
    ram_gb: 8,
    battery_mah: 5100,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Xiaomi|Poco F6 Pro": {
    display: "6.67\" AMOLED",
    display_hz: "144 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },

  // ── Google ────────────────────────────────────────────────────────────────

  "Google|Pixel 9 Pro XL": {
    display: "6.8\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "42 MP",
    processor: "Google Tensor G4",
    ram_gb: 16,
    battery_mah: 5060,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Google|Pixel 9 Pro": {
    display: "6.3\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "42 MP",
    processor: "Google Tensor G4",
    ram_gb: 16,
    battery_mah: 4700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Google|Pixel 9": {
    display: "6.3\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10.5 MP",
    processor: "Google Tensor G4",
    ram_gb: 12,
    battery_mah: 4700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Google|Pixel 8 Pro": {
    display: "6.7\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10.5 MP",
    processor: "Google Tensor G3",
    ram_gb: 12,
    battery_mah: 5050,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Google|Pixel 8": {
    display: "6.2\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10.5 MP",
    processor: "Google Tensor G3",
    ram_gb: 8,
    battery_mah: 4575,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Google|Pixel 8a": {
    display: "6.1\" OLED",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "13 MP",
    processor: "Google Tensor G3",
    ram_gb: 8,
    battery_mah: 4492,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2024,
  },
  "Google|Pixel 7 Pro": {
    display: "6.7\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "10.8 MP",
    processor: "Google Tensor G2",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2022,
  },
  "Google|Pixel 7": {
    display: "6.3\" OLED",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "10.8 MP",
    processor: "Google Tensor G2",
    ram_gb: 8,
    battery_mah: 4355,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2022,
  },
  "Google|Pixel 7a": {
    display: "6.1\" OLED",
    display_hz: "90 Hz",
    camera_main: "64 MP",
    camera_front: "13 MP",
    processor: "Google Tensor G2",
    ram_gb: 8,
    battery_mah: 4385,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2023,
  },
  "Google|Pixel 6 Pro": {
    display: "6.7\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "11.1 MP",
    processor: "Google Tensor",
    ram_gb: 12,
    battery_mah: 5003,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.2", "NFC", "UWB"],
    year: 2021,
  },
  "Google|Pixel 6": {
    display: "6.4\" OLED",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "8 MP",
    processor: "Google Tensor",
    ram_gb: 8,
    battery_mah: 4614,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.2", "NFC", "UWB"],
    year: 2021,
  },
  "Google|Pixel 6a": {
    display: "6.1\" OLED",
    display_hz: "60 Hz",
    camera_main: "12.2 MP",
    camera_front: "8 MP",
    processor: "Google Tensor",
    ram_gb: 6,
    battery_mah: 4306,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC", "UWB"],
    year: 2022,
  },

  // ── OnePlus ───────────────────────────────────────────────────────────────

  "OnePlus|12": {
    display: "6.82\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 5400,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "OnePlus|12R": {
    display: "6.78\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 8 Gen 1",
    ram_gb: 8,
    battery_mah: 5500,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "OnePlus|11": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "OnePlus|Nord 4": {
    display: "6.74\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 7+ Gen 3",
    ram_gb: 8,
    battery_mah: 5500,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "OnePlus|Nord 3": {
    display: "6.74\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Dimensity 9000",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "OnePlus|Nord CE 4": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 7 Gen 3",
    ram_gb: 8,
    battery_mah: 5500,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },

  // ── Oppo ──────────────────────────────────────────────────────────────────

  "Oppo|Find X7 Ultra": {
    display: "6.82\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 7", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "Oppo|Find X6 Pro": {
    display: "6.82\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Oppo|Reno 11 Pro": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Dimensity 8200",
    ram_gb: 12,
    battery_mah: 4600,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Oppo|Reno 11": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "32 MP",
    processor: "Dimensity 6080",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Oppo|Reno 10": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 778G",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Oppo|A98": {
    display: "6.72\" IPS LCD",
    display_hz: "120 Hz",
    camera_main: "64 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 695",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 5", "Bluetooth 5.1", "NFC"],
    year: 2023,
  },
  "Oppo|A79": {
    display: "6.72\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "8 MP",
    processor: "Dimensity 6020",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 5", "Bluetooth 5.1", "NFC"],
    year: 2023,
  },
  "Oppo|A58": {
    display: "6.72\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "8 MP",
    processor: "Helio G85",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.1"],
    year: 2023,
  },

  // ── Honor ─────────────────────────────────────────────────────────────────

  "Honor|Magic 6 Pro": {
    display: "6.8\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "50 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 5600,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Honor|Magic 6": {
    display: "6.78\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 5450,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Honor|90": {
    display: "6.78\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "200 MP",
    camera_front: "50 MP",
    processor: "Snapdragon 7s Gen 2",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.1", "NFC"],
    year: 2023,
  },
  "Honor|70": {
    display: "6.67\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "54 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 778G+",
    ram_gb: 8,
    battery_mah: 4800,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.2", "NFC"],
    year: 2022,
  },
  "Honor|Magic V2": {
    display: "7.92\" OLED (inner)",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 16,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Honor|X8a": {
    display: "6.7\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "100 MP",
    camera_front: "16 MP",
    processor: "Helio G88",
    ram_gb: 6,
    battery_mah: 4500,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0", "NFC"],
    year: 2023,
  },

  // ── Huawei ────────────────────────────────────────────────────────────────

  "Huawei|Pura 70 Ultra": {
    display: "6.8\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Kirin 9010",
    ram_gb: 16,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 6E", "Bluetooth 5.2", "NFC"],
    year: 2024,
  },
  "Huawei|Pura 70 Pro": {
    display: "6.8\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Kirin 9010",
    ram_gb: 12,
    battery_mah: 5050,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 6E", "Bluetooth 5.2", "NFC"],
    year: 2024,
  },
  "Huawei|P60 Pro": {
    display: "6.67\" OLED",
    display_hz: "120 Hz",
    camera_main: "48 MP",
    camera_front: "13 MP",
    processor: "Snapdragon 8+ Gen 1",
    ram_gb: 8,
    battery_mah: 4815,
    sim: "Nano-SIM + eSIM",
    connectivity: ["4G", "WiFi 6E", "Bluetooth 5.2", "NFC"],
    year: 2023,
  },
  "Huawei|Mate 60 Pro": {
    display: "6.82\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "13 MP",
    processor: "Kirin 9000S",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 6E", "Bluetooth 5.2", "NFC"],
    year: 2023,
  },
  "Huawei|Nova 12": {
    display: "6.7\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "60 MP",
    processor: "Snapdragon 778G",
    ram_gb: 8,
    battery_mah: 4500,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 6", "Bluetooth 5.2", "NFC"],
    year: 2024,
  },

  // ── Motorola ──────────────────────────────────────────────────────────────

  "Motorola|Edge 50 Pro": {
    display: "6.7\" POLED",
    display_hz: "144 Hz",
    camera_main: "50 MP",
    camera_front: "50 MP",
    processor: "Snapdragon 7 Gen 3",
    ram_gb: 12,
    battery_mah: 4500,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "Motorola|Edge 40 Pro": {
    display: "6.67\" POLED",
    display_hz: "165 Hz",
    camera_main: "50 MP",
    camera_front: "60 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 12,
    battery_mah: 4600,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Motorola|Edge 40": {
    display: "6.55\" POLED",
    display_hz: "144 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Dimensity 8020",
    ram_gb: 8,
    battery_mah: 4400,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Motorola|Moto G84": {
    display: "6.55\" POLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 695",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.1", "NFC"],
    year: 2023,
  },
  "Motorola|Moto G54": {
    display: "6.5\" IPS LCD",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Dimensity 7020",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["5G", "WiFi 5", "Bluetooth 5.1", "NFC"],
    year: 2023,
  },
  "Motorola|Moto G14": {
    display: "6.5\" IPS LCD",
    display_hz: "90 Hz",
    camera_main: "50 MP",
    camera_front: "5 MP",
    processor: "Helio G85",
    ram_gb: 4,
    battery_mah: 5000,
    sim: "Nano-SIM",
    connectivity: ["4G", "WiFi 5", "Bluetooth 5.0"],
    year: 2023,
  },

  // ── Nothing ───────────────────────────────────────────────────────────────

  "Nothing|Phone (2a)": {
    display: "6.7\" AMOLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Dimensity 7200 Pro",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2024,
  },
  "Nothing|Phone (2)": {
    display: "6.7\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "32 MP",
    processor: "Snapdragon 8+ Gen 1",
    ram_gb: 8,
    battery_mah: 4700,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.3", "NFC"],
    year: 2023,
  },
  "Nothing|Phone (1)": {
    display: "6.55\" OLED",
    display_hz: "120 Hz",
    camera_main: "50 MP",
    camera_front: "16 MP",
    processor: "Snapdragon 778G+",
    ram_gb: 8,
    battery_mah: 4500,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.3", "NFC"],
    year: 2022,
  },

  // ── Sony ──────────────────────────────────────────────────────────────────

  "Sony|Xperia 1 VI": {
    display: "6.5\" OLED",
    display_hz: "120 Hz",
    camera_main: "52 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 3",
    ram_gb: 12,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "Sony|Xperia 10 VI": {
    display: "6.1\" OLED",
    display_hz: "60 Hz",
    camera_main: "48 MP",
    camera_front: "8 MP",
    processor: "Snapdragon 6 Gen 1",
    ram_gb: 6,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6", "Bluetooth 5.4", "NFC"],
    year: 2024,
  },
  "Sony|Xperia 5 V": {
    display: "6.1\" OLED",
    display_hz: "120 Hz",
    camera_main: "52 MP",
    camera_front: "12 MP",
    processor: "Snapdragon 8 Gen 2",
    ram_gb: 8,
    battery_mah: 5000,
    sim: "Nano-SIM + eSIM",
    connectivity: ["5G", "WiFi 6E", "Bluetooth 5.4", "NFC"],
    year: 2023,
  },
};

export function getDeviceSpecs(brand: string, model: string): DeviceSpecs | null {
  return SPECS[`${brand}|${model}`] ?? null;
}
